### ISSUE TITLE
需要改进的地方

### ISSUE THREAD

**Issue by Mapaler** [ChinaKevinLi/PixivSync#1]
问题实在太多，只写出我记得起来的部分

1. 主动提示安装库，最好做成自动检测安装，如果py版本不对做出提示。
1. 询问是否保存账号密码，并径允许后保存，之后除非用修改参数重新修改默认账号，否则不要让人输入。另外可以用命令临时改变账号密码`--user XXXX --pass XXXX`。
1. 输入密码前提示`输入或粘贴完成后按回车`，并按回车后显示`正在登陆`，不然还以为卡死了。
1. 登陆保存Token，Token可用的情况下不要进行重复登陆以节省账号的Token数量（就算获取了新Token，旧Token到期前还是可以一直访问的）。
1. 没有参数时，询问账号密码/登陆后，显示`输入 1 2 3 4 执行XXXX操作`，避免一定要输入参数。因为我可以直接执行py文件。
1. 执行`--help`、`-h`、`/h`、`/?`这些参数时输出帮助，使用方法不要只写在README。
1. 参数单独指定下载某个作者或作品。
1. `database`文件加上扩展名，比如`.db`、`.db3`、`.s3db`。
1. 会随用户变动的文件不要加到版本控制，添加到`.gitignore`里面去，如果数据库必须要一个初始文件的话可以用代码检测没有就生成，或者从版本控制的`default.db`复制一份到非版本控制的`database.db`，不然用户拉新版本代码会冲突。下载文件夹也添加到`.gitignore`里。`.gitignore`自身可以添加到版本控制
1. 下载进度太杂乱，完全不知道进度。可以将CMD标题修改为`当前正在下载 作者XXX(3/12) 的 XXX(20/108) 共(1234/12345)`
1. 图源版本保持一致，可以用参数设定下载质量，要么都是高清，要么都是原图。
1. 数据库的更新没看懂什么意思，要是我来做SQL，我会做作者一个表，作品一个表，作品里每一项记录作者id。每个作者有一个表示获取完成的布尔值，如果数据库有该作者，且该值为假，则进行完整的获取或者断点续传，获取完成后标记为真，表示这个作者在当前状态已经获取完成了。下次更新时如果是完成为真的作者，就可以先得到作者的作品中最大的ID，这样更新数据就可以增量更新，发现有这个id后就停止向P站请求数据。但是需要提供一个强制更新的参数，因为作者有可能会重投稿老的图片。

**Comment by Mapaler** [comment]
https://github.com/search?l=Python&q=pixiv&type=Repositories
我不会py没法给出程序建议，Github有这么多py写的，你自己多参考参考吧

**Comment by KernelErr** [comment]
感谢。这几天把这些问题一一修复。

**Comment by KernelErr** [comment]
I have thought about this issue for several times, and I decided to create a new tool which can allow users to download images from Pixiv **without** VPN or any proxy. Thanks for staying focusing on this project.

**Comment by Mapaler** [comment]
你给我发英文干啥
